# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Main Pipeline

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    env:
      TmdbApiKey: ${{ secrets.TMDBAPIKEY }}
      SpotifyClientId: ${{ secrets.SPOTIFYCLIENTID }}
      SpotifyClientSecret: ${{ secrets.SPOTIFYCLIENTSECRET }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore ./cinema.log.server/cinema.log.server.sln
    - name: Build
      run: dotnet build ./cinema.log.server/cinema.log.server.sln --no-restore
    - name: Test
      run: dotnet test ./cinema.log.server/cinema.log.server.sln --no-build --verbosity normal
